### ISSUE TITLE
problem with language!!!

### ISSUE THREAD

**Issue by revoltown** [Piwigo/piwigo-flutter-app#125] opened 2022-06-19 12:09 UTC
Hi there each time I download and install Piwigo I get German language, like to have polish or English please help....

**Comment by remi-martin** [comment] 2022-06-20 07:41
Hi, language is supposed to be linked with your device system language. This is a known issue and we are already investigating on it.

**Comment by remi-martin** [comment] 2022-06-20 07:53
Please, can I know your device, your system language and android version

**Comment by lisbonresearch** [comment] 2022-06-21 14:23
Same here, probably because german is the first file in /lib/l10n. I had my device in a different language and the app was in german. Then I changed my device's language to english and the app changed to english.

You should be able to reproduce this if you change your device's language to one that doesn't have translations in /lib/l10n.

I guess what's missing is setting the default/fallback language to english.

**Comment by remi-martin** [comment] 2022-06-27 07:30
Hello, I'm working on it and it should be fixed soon.

**Comment by remi-martin** [comment] 2022-07-13 06:52
Hi, Piwigo NG v1.1.0 is in review and should be available soon.
This update will add a way to choose the application language through the settings.

**Closed** 2022-10-17 07:13 UTC
Labels: bug, probably fixed
