### ISSUE TITLE
Scroll Progress reset after viewing a photo

### ISSUE THREAD

**Issue by Nologist** [Piwigo/piwigo-flutter-app#153] opened 2023-04-26 12:01 UTC
Hi there,

I've tested Piwigo NG Beta V2.0.2 on a Samsung Galaxy Flip 3, retrieved from the official PlayStore as a participant of the Beta program.
It's a nice step forward when comparing to v1. Congratulations! I really like the Design and the fluent performance!

However there's a major issue I'd like to address. 
Whenever I return from an original sized picture to the overview/album view, the entire scrolling progress is being reset, so that you're getting to the beginning of the Album.
Thus, one need to repeat the entire scrolling (and lazy loading) procedure again to get where you stopped previously.
This depreciate the entire UX because scrolling through albums and watching particular photos in full size is literally one of the most important core features of every photo App. 

As I'm not familar with Flutter, I'm not aware of the required efforts and challenges with this. But I'm sure it's worth it.

Looking forward to a solution.

Thanks and keep up the great work!

Best 
Sven

**Comment by remi-martin** [comment] 2023-05-02 12:24
Oh I see, so you'd like the app to remember where you scrolled on an album page before you opened the full-screen page or another album ? Or at least, animate the scroll to the element you pressed

**Comment by remi-martin** [comment] 2023-05-10 09:52
I made some tests with the latest version of Piwigo NG (2.0.3) and it seems it is already working. Just in case, I added something that should do it anyway. Stay tuned for the next update.

**Comment by Nologist** [comment] 2023-05-19 11:41
Sounds good to me. Thanks :)
Just to make sure I got it right: This feature should be available in v 2.0.3? 
I'm just asking because this build number was already out and installed on my phone when I created this issue. 
Does it mean it won't work on my device or is the current 2.0.3. beta version on Google Play just a previous build that was missing this feature at the time?

**Comment by Nologist** [comment] 2023-05-31 19:24
Hi,

just wanted to let you know that, unfortunately, it still doesn't remember the scroll progress, even in 2.0.4 Beta from Google Play.
Maybe I misunderstood your comment, but it definetly should work with 2.0.4, shouldn't it?

**Comment by remi-martin** [comment] 2023-05-31 19:55
I don't know because it works for me...
- I click on a photo thumbnail
- It opens the image preview in full-screen
- I close the page and it go back to where I clicked

**Comment by Nologist** [comment] 2023-06-01 09:19
Just as an example with some arbitrary numbers:

Let's say you have an album with 200 photos. The app initially loads some of them at the beginning, right? Let's say _50_ at once.
When you scroll further, the next bunch of _50_ photos will be loaded on the fly.
So when you want to view photo number 185, there'll be three more reloadings in total.
Assuming I've scrolled to the very bottom of the album, I would see the photos 150 to 200. Next I click on thumbnail 185 to get the full-screen preview. Now, when I return to the album, I would expect to return to the exact position, getting 150-200 shown again. 
That's not the case, though. Except the first 50 images, all other images disappear and will require another three reloadings to get shown again.

**Comment by remi-martin** [comment] 2023-06-01 09:24
Oh, so the issue is with the pagination... I see what I can do

**Comment by Nologist** [comment] 2023-06-01 09:27
Yes. Sorry. That little word made the difference. 
Thank you!

**Comment by Nologist** [comment] 2023-06-26 21:13
Hi.

I'm just curious if there is any news on this?

If the "seamless" pagination doesn't allow continuation as described, it might be an option to go with the "classic" approach (page numbers at the bottom) for now.
I actually would still prefer the seamless one, however everything else is better than being thrown to the beginning of an album whenever you decide to view a fully sized photo.

Best
Sven

**Comment by remi-martin** [comment] 2023-06-27 13:32
Hi, this should be fixed with 2.1.0. Now the app remembers the pagination.

**Comment by Nologist** [comment] 2023-06-27 17:57
Perfect!!
Waiting for the release. 

Thanks for your great support!

**Comment by remi-martin** [comment] 2023-07-03 07:36
*Note : when back from image preview, if the last previewed image is different from the one we clicked in the album, it will not scroll to that last image, but stay where we clicked.*

An improvement would be to scroll the last image previewed thumbnail when we press back.

**Comment by Nologist** [comment] 2023-07-03 08:25
Yes - that's it. Now it feels way more comfortable and intuitive!  
Thanks very much! Good work.

Just to let you know - the thumbnails are being reloaded everytime I return from a preview. It doesn't bother me personally, however it might affect lower-end devices.

In addition, I've noticed sudden app crashes while scrolling through large albums, especially when I open image previews and return to the album many times. I'm not sure whether this bug is new or an existing one that was just enhanced by the latest changes. However I'm pretty sure there's a memory leak somewhere, because just before the app crashes, several background processes are terminated.

Regarding your note: I don't think it's a big deal, as long as it feels consistent. 
And in either case it's just a matter of taste, I think.

**Comment by remi-martin** [comment] 2023-07-17 07:31
Hi,

The other issues are related to the image cache. I'm currently trying to fix app crashes when too much images are displayed but it's a mess. You might see some changes about this in the next updates...

**Closed by remi-martin** 2023-07-17 07:31 UTC
Labels: feature

**Comment by Nologist** [comment] 2023-07-17 20:31
Excellent.
Thanks for your efforts!
And, again, keep up the great work!

Best
Sven
